### ISSUE TITLE
Label names not found

### ISSUE THREAD

**Issue by yzhan238** [ZihanWangKi/x-TC#2]
There is no the label names file for the datasets from Huggingface

**Comment by wtl666wtl** [comment]
Sorry for that, but you can find them in the appendix of our paper.

**Comment by wtl666wtl** [comment]
I can also provide them here.

[imdb.txt](https://github.com/ZihanWangKi/x-TC/files/13370852/imdb.txt)
[yelp_review_full.txt](https://github.com/ZihanWangKi/x-TC/files/13370854/yelp_review_full.txt)
[yelp_polarity.txt](https://github.com/ZihanWangKi/x-TC/files/13370855/yelp_polarity.txt)
[ag_news.txt](https://github.com/ZihanWangKi/x-TC/files/13370856/ag_news.txt)
[dbpedia_14.txt](https://github.com/ZihanWangKi/x-TC/files/13370857/dbpedia_14.txt)
